### ISSUE TITLE
如何在rockylinux9系统上使用

### ISSUE THREAD

**Issue by szppp** [Berrysoft/tunet-rust#101]
提供的linux安装包只有ubuntu的，但是我的系统是rockylinux9（redhat系，是centos的继任者）。尝试了用alien把tunet.jammy.x86_64.deb转化为rpm包，但是rpm安装时会提示缺少libm.so.6(GLIBC_2.35)，而系统自带的glibc是2.34。尝试手动编译了glibc-2.35并添加了LD_LIBRARY_PATH环境变量，但安装时就会报错Segmentation fault (core dumped)。tunet.focal.x86_64.deb转化的包同样会缺少依赖。所以在考虑从源码编译，请问该如何编译？或者有没有其它方法可以解决？谢谢！

**Comment by Berrysoft** [comment]
我没有用过 rockylinux9，不过先看看你的发行版有没有提供 rust。如果不提供，可以通过 [rustup](https://rustup.rs/) 安装。之后可以按照 README 里面写的[编译说明](https://github.com/Berrysoft/tunet-rust#%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E)编译。

**Comment by szppp** [comment]
好的，谢谢！我去试一下
