### ISSUE TITLE
希望能添加断线重连的功能

### ISSUE THREAD

**Issue by jsbyysheng** [Berrysoft/tunet-rust#163]
学校的有线网就算定时去ping外网地址，还是会断线，能不能定时检测外网状态，断线自动重连？

**Comment by Berrysoft** [comment]
`tunet-service` 是有断线重连功能的，不过依赖于系统对于连接状态的理解。一般来说是工作的。

**Comment by jsbyysheng** [comment]
> `tunet-service` 是有断线重连功能的，不过依赖于系统对于连接状态的理解。一般来说是工作的。

如果是多网口的服务器，能不能选择从哪个inrerface连接？

**Comment by Berrysoft** [comment]
简单来说，不能。

**Comment by Berrysoft** [comment]
复杂来说，目前想不好怎么做。并没有一种特别漂亮的方式做这个功能。建议把校园网设置成 default interface。

**Comment by jsbyysheng** [comment]
> 复杂来说，目前想不好怎么做。并没有一种特别漂亮的方式做这个功能。建议把校园网设置成 default interface。

好的，感谢感谢🙏，还有个小小的疑问，不知道大佬有没有兼容openwrt的打算，对于实验室的局域网，能挂在路由器上是最方便的。

**Comment by Berrysoft** [comment]
Rust 对 mips*-unknown-linux-uclibc 的支持都是 Tier 3：

https://doc.rust-lang.org/nightly/rustc/platform-support.html

可以尝试自行交叉编译。

**Comment by jsbyysheng** [comment]
> Rust 对 mips*-unknown-linux-uclibc 的支持都是 Tier 3：
> 
> https://doc.rust-lang.org/nightly/rustc/platform-support.html
> 
> 可以尝试自行交叉编译。

okok

**Comment by jsbyysheng** [comment]
> 复杂来说，目前想不好怎么做。并没有一种特别漂亮的方式做这个功能。建议把校园网设置成 default interface。

我想到一个折中的办法，用docker，开2个container，分别制定不同的interface，233333
