### ISSUE TITLE
第一次登陆成功，后面再登陆提示密码错误？

### ISSUE THREAD

**Issue by fandong1993** [Berrysoft/tunet-rust#36]
system os: debian 10 x64
kernel: linux 4.9
repeatable: yes
问题：第一次登录时，提示输入密码，一切正常，输入后登陆成功；然后下线后，后面再次登陆，就提示密码不对，但是密码就是第一次登陆时保存的啊。请作者帮忙看一下，谢谢。

**Comment by Berrysoft** [comment]
1. 用的是命令行、控制台 cui 还是图形界面 gui？
2. 是否尝试过使用命令行 `tunet deletecred` 删除密码并且重新操作？
3. 在不关闭 cui 或 gui 的情况下，登录成功之后下线再登录，是否会提示密码不对？

**Comment by Berrysoft** [comment]
快一年了没有回复，关了。有问题可以重新打开。
