### ISSUE TITLE
无法保存密码，每次都需要重新输入密码

### ISSUE THREAD

**Issue by GJCav** [Berrysoft/tunet-rust#67]
运行环境：Ubuntu20.04
版本：0.8.1

使用工具：tunet 命令行版本

问题描述：第一次使用 `tunet login` 后提示输入用户名和密码，输入后成功登陆。再次使用 `tunet login` 时不需要输入用户名，但提示输入密码。但按照 README 文档 tunet 应该是能够储存密码到本地的。

补充：使用 `systemctl enable tunet@my_account_name` 后使用 `systemctl status tunet@my_account_name` 查看状态，显示

```
JSON 解析错误：EOF while parsing a value at line 1 column 0
```

似乎程序没能成功储存密码。

**Comment by Berrysoft** [comment]
这个问题分为两部分。

1. 在 Linux 上保存密码使用的是内核的 keyring。这样做是出于开发的简便和兼容性考虑。`keyring` 包本身还有一个使用 secret-service 保存密码的特性，但是目前并没有打开。你需要这样的功能吗？
2. 请使用 `systemctl enable tunet@user_name` 。`@` 后面应该是你系统的用户名，使用这个来找到已经保存的用户名配置。

**Comment by Berrysoft** [comment]
另外请检查你 `~/.config/tunet/settings.json` 文件内容？里面应该是一个合法的 JSON。

**Comment by GJCav** [comment]
补充说明：`systemctl status tunet@root` 显示 密码管理错误：No matching entry found in secure storage

~/.config/tunet 下存在合法json

似乎是确实是因为 secret-service 没打开，请问我应该如何打开这个功能？

**Comment by Berrysoft** [comment]
不应该是root，应该是你linux的用户名。

有关secret-service，需要改编译选项，我来研究一下。

**Comment by Berrysoft** [comment]
虽然有点麻烦，但是我建议先解决tunet-service拿不到保存的用户名的问题。如果它拿到了用户名，之后的log应当能给出为什么无法保存密码的错误信息。

**Comment by GJCav** [comment]
> 不应该是root，应该是你linux的用户名。
> 
> 有关secret-service，需要改编译选项，我来研究一下。

我明白了，我之前一直在使用 root 账户，使用其他账户就没有这个问题了。

非常感谢！！这个项目对我帮助很大
