### ISSUE TITLE
重启后丢失记录的密码

### ISSUE THREAD

**Issue by GJCav** [Berrysoft/tunet-rust#71]
运行环境：Ubuntu20.04
版本：0.8.1

使用工具：tunet 命令行版本

问题复现：
登录 Ubuntu20 系统，在控制台中使用 `tunet login` 正常登录，然后启用服务 `sudo systemctl enable tunett@jcav`，经过测试服务能够正常读取保存的密码自动登录校园网。
但重启系统后，测试发现无法自动登录校园网，使用 `systemctl status tunet@jcav` 查看日志输出如下：

![Screenshot from 2023-07-02 01-44-01](https://github.com/Berrysoft/tunet-rust/assets/24679507/129811d8-6a2f-40dc-9e52-35796922e175)

**Comment by Berrysoft** [comment]
这是一个已知问题，即 Linux Kernel Keyring 可能在重启后丢失。目前还在调查原因。

暂时的解决办法就是开机的时候手动设置一次吧。其实在 Windows 上和 macOS 上这个服务也存在开机之后可能连不上网的问题，虽然不是同一个原因。

**Comment by Berrysoft** [comment]
上游： https://github.com/hwchen/keyring-rs/issues/137

**Comment by GJCav** [comment]
了解了，请问可否使用其他方法储存密码，或者使用命令行参数指定用户名、密码

**Comment by Berrysoft** [comment]
出于安全原因没有提供命令行指定的方法。我计划等待一下上游的回复，如果这是 Linux 内核的固有问题，就考虑改成用文件明文保存密码好了。

**Comment by Berrysoft** [comment]
@GJCav 您好，能在您的系统中使用命令 `cat /proc/keys` 看一下吗？这个命令不会泄露密码（但是会出现您的校园网用户名）。

在保存过密码之后，应该会有一行的最后一项有 `keyring-rs:<校园网用户名>@tunet: <数字>` 的形式。能给出这一行的完整信息吗？

**Comment by Berrysoft** [comment]
过段时间发新版。

**Comment by Berrysoft** [comment]
已经发布新版本。需要使用命令行工具重新设置密码。
